trigger:
- main

pool: selfhosted

stages:
- stage: initplan
  displayName: terraform init & plan
  jobs:
  - job: initplan
    displayName: terraform init & plan
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendServiceArm: 'Manchal-gen'
        backendAzureRmResourceGroupName: 'window-storage'
        backendAzureRmStorageAccountName: 'chayanstorage'
        backendAzureRmContainerName: 'chayan'
        backendAzureRmKey: 'abc.terraform.tfstate'
    
    
    

      
