trigger: none
pool: selfhosted
stages: 
- stage: initandplan
  displayName: init & plan
  jobs:
  - job: initandplan
    displayName: init & plan
    steps:
     - task: TerraformInstaller@1
       inputs:
         terraformVersion: 'latest'
     - task: TerraformTaskV4@4
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)\env\dev'
         backendServiceArm: 'Manchal-gen'
         backendAzureRmResourceGroupName: 'window-storage'
         backendAzureRmStorageAccountName: 'chayanstorage'
         backendAzureRmContainerName: 'chayan'
         backendAzureRmKey: 'abc.terraform.tfstate'
- stage: terraformapply
  jobs:
  - job: terraformapply
    displayName: terraform apply
    steps:
     - task: TerraformTaskV4@4
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)\env\dev'
         backendServiceArm: 'Manchal-gen'
         backendAzureRmResourceGroupName: 'window-storage'
         backendAzureRmStorageAccountName: 'chayanstorage'
         backendAzureRmContainerName: 'chayan'
         backendAzureRmKey: 'abc.terraform.tfstate'
     - task: TerraformTaskV4@4
       inputs:
         provider: 'azurerm'
         command: 'apply'
         workingDirectory: '$(System.DefaultWorkingDirectory)\env\dev'
         commandOptions: '-auto-approve'
         environmentServiceNameAzureRM: 'Manchal-gen'

      
